### PR TITLE
chore(cmake): make Catch2 optional as it's only needed for testing

### PR DESCRIPTION
**Pull request by anarchuser**

### CODE REVIEW

**Review by xeruf — APPROVED** [review]

**Comment by xeruf** [comment]
This is not a `feat` my dear ;)

**Comment by xeruf** [comment]
Tests work fine, currently don't know how to test without catch2 because I don't know how I installed it ^^

**Comment by anarchuser** [comment]
I wasn't sure how to call it.
What'd you say? A chore?

**Comment by anarchuser** [comment]
In a way it's a fix; it shouldn't have ever been a dependency for building the source

**Comment by xeruf** [comment]
Please look into https://karma-runner.github.io/5.0/dev/git-commit-msg.html again, it is pretty obviously stated :)

**Comment by anarchuser** [comment]
Then I guess I'm just blind.
Would you be so kind to explain what exactly you mean?

**Comment by xeruf** [comment]
feat (new feature for the user, **not a new feature for build script**)
fix (bug fix for the user, **not a fix to a build script**)

-> chore (updating grunt tasks etc; no production code change)

**Comment by anarchuser** [comment]
alright, thanks

**Pull request merged**
