### PR TITLE
feat(model): add modifiers to methods (nodiscard, const, override)

### PR DESCRIPTION
**Pull request by anarchuser**
see [e245148](https://github.com/Xerus2000/eve/commit/e245148ead848231bf7a9fd83372b214d34ea83c).

Also, while adding the const modifiers to terminalview, I took the freedom to change two loops to for-each loops (as an example of fancy C++14 feats XD)

### CODE REVIEW

**Comment by AtomToast** [comment]
I will try to remember those loops. They look way cleaner.

What exactly do all these changes do?

**Comment by anarchuser** [comment]
> see [e245148](https://github.com/Xerus2000/eve/commit/e245148ead848231bf7a9fd83372b214d34ea83c).

Basically, I made a few things constant which should be, like getters.
that allows these methods to be invoked from a const reference

**Comment by AtomToast** [comment]
ah, so basically it makes const objects usable beyond accessing public variables?

**Comment by AtomToast** [comment]
ah, so basically it makes const objects usable beyond accessing public variables?

**Comment by anarchuser** [comment]
> ah, so basically it makes const objects usable beyond accessing public variables?

yes, since the `const` asures a function doesn't modifies anything

**Review by AtomToast — APPROVED** [review]

**Pull request merged**
